### ISSUE TITLE
use the new projects?

### ISSUE THREAD

**Issue by kjappelbaum** [nanotech-empa/general-issues#3]
again, unsolicited feedback ;) 

if you use the [organization-wide project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/creating-a-project#creating-an-organization-project) you can track issues across multiple repos in a organization 

You can also add items without creating an issue in a repo.

**Comment by yakutovicha** [comment]
Hey @kjappelbaum, thanks :)

> if you use the [organization-wide project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/creating-a-project#creating-an-organization-project) you can track issues across multiple repos in a organization

We use it already 😎. Projects are our main management tool at the moment.

> You can also add items without creating an issue in a repo.

It's exactly what we don't want. We want to discuss an issue. Item in a project doesn't have a discussion possibility unless converted to an issue.

**Comment by yakutovicha** [comment]
Unless there are no other suggestions or follow-ups, I close the issue.
