### ISSUE TITLE
Don't forget adding %load_ext tutorial.tests.testsuite

### ISSUE THREAD

**Issue by baffelli** [nanotech-empa/general-issues#7]
I noticed that most notebooks don't use the cell magic `%load_ext tutorial.tests.testsuite`. We should add it at the top of every notebook. However, we also should remind people to run all cells above before working on their exercises, otherwise this won't work.

**Comment by yakutovicha** [comment]
@baffelli just noticed this issue. I think you wanted to put it somewhere else.
